### ISSUE TITLE
Translation to Chinese: Liberation Through Radical Decentralization

### ISSUE THREAD

**Issue by bobjiang** [HiBlock/blockchain-learning#13]
https://medium.com/@VitalikButerin/liberation-through-radical-decentralization-22fc4bedc2ac

Liberation Through Radical Decentralization
By Vitalik Buterin and Glen Weyl

Wealthy societies around the world are facing a growing crisis of confidence in established authorities. Stagnating economies, mounting inequality, political corruption and the increasing monopolization of technology for the benefit of elites have provoked a populist backlash. We share and are driven by these feelings of discontent. However, we also fear that the most common responses on both the right and the left (a retreat from technology, markets and international cooperation) would destroy much of what we treasure in contemporary society while worsening the problems they seek to solve. Over the last half decade, each of us has, in his own way, been working on a part of an alternative solution: to find ways to harness markets and technology to radically decentralize power of all sorts and shift our reliance from authority and to formal rules. In what follows, we discuss how these projects interrelate and complement each other.

One of us has focused on technological solutions to the increasingly centralized control that has been established by powerful monopolies in the digital economy and financial spheres. Bitcoin and other cryptocurrencies in particular emerged directly as a reaction to the perceived excesses of the traditional financial system, with “The Times 03/Jan/2009 Chancellor on brink of second bailout for banks” carved indelibly into Bitcoin’s genesis block. That said, the decentralized technologies behind cryptocurrencies have potential applications far beyond finance. The news is filled with the failures of centralized systems to protect people’s privacy, ranging from large-scale hacks such as Equifax to more recent concerns around social media privacy. Such events are increasing interest and innovation in “self-sovereign” user-centric identity management systems; the use of a blockchain as an expensive but decentralized and very high-assurance store of data and computation features often in such designs.

The other has focused on designing rules of the economic and political games of mainstream society, aiming to both break up and reduce the need for concentrated centralized authority — what he calls “Radical Markets”. Traditional private property tends to create and perpetuate inequality of power, monopolizing resources in a few hands rather than deploying them to their best uses. A truer, radical free market would create greater competition and equality by a greater use of auctions and commonly owned property. One-person-one-vote democracy tends to oppress minorities, who then seek protection from the judicial system or international authorities, thus subverting democracy. A more creative democratic forms that give power to minorities to protect their own most deeply valued interests can restore the legitimacy of government. A leading candidate is “Quadratic Voting” (QV), in which citizens can use a (possibly artificial) currency to buy votes at the cost of the square of the votes bought on the issues that are most important to them.

Our projects developed largely separately and each of us has hesitations about especially the near-term aspects of the other’s project. For all their potential, cryptocurrencies show dangerous tendencies towards bubble behavior and the precise set of use cases in which they make the most sense remain to be worked out. Radical new kinds of social institutions, whether technical or economic or political, top-down or bottom-up, are best adopted incrementally and slowly, to give opportunity for experimentation and social learning and reduce the risk that they might disrupt existing social structures in a way that would cause precisely the sort of conflict they seek to heal.

Yet both of us also see great potential for collaboration and complementarity between our programs. Because Ethereum and other cryptocurrencies (intentionally) lack trusted judges and other authorities to adjudicate disputes, they depend heavily on formal and transparent rules. The failings of standard property and voting rules quickly manifest themselves when stripped of the protective coating of human-driven judicial discretion. Blockchain-based projects therefore have a strong demand for better rules that can help to maintain the decentralization of economic power and for governance rules that can avoid the need for large bureaucracies these communities cannot support; a Radical Market that can operate successfully on the blockchain is one that most fully achieves the goal of avoiding reliance on discretionary power. Finally, the cryptocurrency community is one with aligned philosophical values, and an unusual openness to innovation, that makes it an ideal place where Radical Market ideas can be tested at relatively limited broader social cost.

We thus see many opportunities to collaborate and are actively working to foster connections between our respective communities. Even if neither community achieves its sweeping social ambitions, there are a wide range of narrower contexts where collaborations seem capable of making important social impacts, including using blockchains to improve security of data markets and QV for aggregation of opinions in blockchain-based social networks. And beyond the specific ideas we have worked on, a range of related collaborations seem possible, from using electronic “postage” to deter spam to expanding access to high-quality financial planning for those with limited resources.

One particular example of a possible area for collaboration, and which illustrates some of the challenges involved, is the use of QV to address the substantial governance problems blockchain-based communities have faced. There have been many attempts to use votes to gauge community sentiment when deciding on potentially controversial protocol changes, but so far they have been criticized either for being too vulnerable to manipulation by sockpuppets (fake accounts) and malicious voting by non-community-members or for being too skewed toward reflecting the views of a small group of wealthy coin holders. Some form of QV could present a moderate alternative, as participants’ differing strength of views and stake in the community are taken account, but because the cost of buying many votes quickly becomes prohibitive (1000 votes would cost 1,000,000 credits) the ability for a small elite to disproportionately affect outcomes is limited.

However, QV also poses important technical and conceptual challenges to existing crypto-currency communities. In particular, QV relies heavily on the notion of verifiable, separate human identities, because a community member could multiply her effective influence dramatically by misrepresenting herself as multiple individuals (sockpuppets). The frequent use of anonymity and pseudonymity in crypto-currency communities is in tension with the need for such clearly-delineated identities, though also naturally gives rise to some of the inegalitarian wealth and power dynamics these communities hoped to avoid. After all, a system that formalizes only capital and not human individuality may inexorably serve wealth rather than humanity. In this sense, experiments with Radical Markets may help clarify important outstanding technical questions within crypto-currency communities.

More generally, as we have arguably seen with parts of the internet and the web, excessive and naïve reliance on any formalism intended to decentralize authority can inadvertently have the perverse effect of reestablishing monopolies and oligarchies. Only by making technical systems that offer a variety of mechanisms for checking concentrations of power and by simultaneously building social ideologies constantly on the lookout for failure modes of these mechanisms can we hope to succeed where previous attempts at decentralizing authority have failed. But we are hopeful that some combination of blockchain and Radical Markets technologies can make an important contribution to breaking up the most oppressive forms of corporate, government and technical power and building towards a more free, open and cooperative world in the 21st century.

**Comment by bobjiang** [comment]
anyone is working on this?

**Comment by buffalo2004** [comment]
Hi,  I would like to do it. When will I cpmplete this work?

**Comment by bobjiang** [comment]
it's up to your plan, normally asap.

**Comment by buffalo2004** [comment]
世界各地的富有社会正面临着对现有权力机构日益加剧的信任危机。经济停滞、不平等加剧、政治腐败以及为精英利益而日益垄断的技术引发了民粹主义的反弹。我们分享并被这些不满情绪所驱使。但是，我们也担心在左右两边（技术、市场和国际合作的倒退）最常见的反应会破坏我们在当代社会珍惜的大部分东西，同时使得他们寻求解决的问题更加严重。在过去的五年中，我们每个人都以自己的方式一直在寻找替代解决方案的一部分：寻找利用市场和技术从根本上去除各种中心化权力的方式，并将我们对权威的依赖转移到正式规则中。在接下来的内容中，我们将讨论这些项目如何相互关联和相互补充的。
我们其中的一位专注于技术解决方案，以应对由数字经济和金融领域的强大垄断者所建立的日益中心化操控。特别是比特币和其他加密货币的出现，这是对传统金融体系过度行为的直接反应，“2009年1月3日泰晤士报,首相第二次对处于崩溃边缘的银行进行紧急救助”这句话不可磨灭地印刻在比特币的创始块中。也就是说，加密货币背后的去中心化技术具有远不止在财政金融方面的潜在应用。这个消息充斥着中心化系统保护人们隐私的失败，表现在像Equifax等大规模黑客到近期对社交媒体隐私的担忧等等。此类事件正在刺激着对以用户为中心的自主性身份管理系统的兴趣和创新；这种设计通常具有昂贵且去中心化的区块链、非常可靠的数据计算两个特征。
另一位则侧重于设计主流社会的经济和政治游戏规则，旨在打破和减少对中心化权力的需求-他称之为“完全市场”。传统的私人财富倾向于创造并延续着掌握在少数人手中的不平等权力、垄断资源，而不是将它们用于最佳用途。更真实、完全的自由市场将通过更多地使用拍卖和共同拥有的财产来创造更好的竞争和平等。一人一票民主倾向于压迫少数人群，这些少数人群向司法系统或国际当局寻求保护，这就颠覆一人一票民主。有一种能够赋予少数人群权力并保护他们最珍贵利益的更具创造性的民主形式，它可以恢复政府的合法性。一个主要民主形式的潜在候选者是“二次方投票”制度（QV），公民可以使用（可能是人造的）货币购买选票，其出价为以他们认为对自己最重要的议题来进行购买票数的平方。
我们的项目在很大程度上分开开发，我们每个人都对其他项目的近期发展方向有所犹豫。尽管潜力巨大，加密货币显示出产生泡沫行为的危险倾向，并且他们最有意义的确切用例仍然需要进行研究才能产生。激进的新型社会制度，无论是技术的、经济的或者政治的，无论是自上而下的还是自下而上的，都是在逐步缓慢地采用，为试验和社会学习提供机会，并降低它们可能破坏现有社会结构的风险，这种方式会精确导致他们寻求治愈的那种冲突。
然而我们两个人也看到这两个计划之间存在很大的合作潜力和互补性。由于以太坊和其他加密货币（主观性）缺乏值得信任的裁决和其他的权威裁决纠纷，因此他们必须严重依赖正规和透明的规则。当剥夺了人为驱动的权威裁决权的保护外衣时，标准财产和投票规则的失败就会迅速显现出来。因此，基于区块链的项目对更好的规则存在强烈的需求，这些规则可以帮助维持经济权力的去中心化，以及可以避免需要社区无法支持的大型官僚机构的治理规则；这是一个可以在区块链上成功运作的完全市场，可以最大程度上实现避免依赖自由裁量权的目标。最后，加密货币社区具有统一的哲学价值观和对创新的不同寻常的开放性，这使得它成为完全市场理念可以在相对有限的更广泛的社会成本下进行测试的理想场所。
因此，我们看到了许多合作机会，并积极努力加强我们各自社区之间的联系。 即使两个社区都没有实现其全面的社会目标，一系列范围较窄的合作也似乎能够产生重要的社会影响，包括使用区块链来提高数据市场的安全性和在基于区块链的社交网络中聚合意见的QV。除了我们已经在做的具体想法，一系列相关合作似乎也是可能的，例如从使用电子“邮资”来阻止垃圾邮件到为扩大资源有限人群获得高质量财务计划的机会。
有一个可能合作领域的特例子，它阐述了一些有关挑战，这个例子就是使用QV来解决区块链社区面临的实质性治理问题。在决定可能引起争议的协议变更时，曾经有很多尝试使用投票来评估社区情绪，但迄今为止批评他们太容易受到盗版（假帐户）的操纵和非社区成员的恶意投票，或者因为太过于倾向于少部分富有持币者的观点。某些形式的QV可以提供一种温和的选择，因为要考虑参与者在社区中的不同观点和权益，但是因为购买许多选票的成本很快变得过高（1000票将花费1,000,000个信用），这对结果影响不成比例的少数精英的能力受到限制。
但是，对现有的加密货币社区QV也提出了重要的技术和概念上的挑战。特别是，QV严重依赖于可验证的、各自身份识别的概念，因为社区成员可以通过将自己假装为多个人（盗版）来夸大其有效影响力。密码货币社区中频繁使用匿名和假名的情况与这种明确界定的身份密切相关，但也自然引起了这些社区希望避免的一些财富不平等和权力变动。毕竟，仅规范资本而不规范人类个人行为的制度可能无情地只能为财富而不是人类服务。从这个意义上说，完全市场的实验可能有助于澄清加密货币社区中重要的突出技术问题。
更普遍的是，正如我们在互联网和网络中可以看到的那样，过度和天真地依赖任何旨在给权威去中心化的形式主义，这可能会无意中产生重建垄断和寡头政治的不利影响。只有通过建立能够进行各种检查权力集中的技术体系，并通过不断建立社会意识形态来寻找这些机制的失败模式，我们才能希望在权力去中心化失败的情况下取得成功。但我们希望，区块链和完全市场技术的某种组合能够为打破最具压迫性的企业、政府和技术力量，同时为建立更加自由、开放和合作的21世纪世界做出重要贡献。

**Comment by buffalo2004** [comment]
姜总，翻译完成，已经提交！通过GitHub提交的时候，首先克隆你的repository，没有发现blockchain-learning，先以这种方式提交给您，不好意思。

**Comment by buffalo2004** [comment]
Metamask地址：
0x1903d83dedEFeDaf6cfEE5828E7e66AE6A2E1D97
